### ISSUE TITLE
Can't install on Mac OS X El Capitan Node v4.2.4

### ISSUE THREAD

**Issue by GentryRiggen** [arvydas/blinkstick-node#21]
Failed at the usb@1.0.4 install script 'node shyp-blacklist.js win32-x64 win32-ia32 darwin-x64 || node-gyp rebuild'.

**Comment by arvydas** [comment]
This is fixed with latest release.

**Comment by GentryRiggen** [comment]
I can confirm. Thank you!  
  

Gentry

> On Feb 23 2016, at 1:43 am, Arvydas Juskevicius
&lt;notifications@github.com&gt; wrote:  

>

> This is fixed with latest release.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/arvydas
/blinkstick-node/issues/21#issuecomment-187603093).![](https://github.com/noti
fications/beacon/AGAbm9TCO01Vn5OHx3bExVfk21WBCHAsks5pnBMqgaJpZM4HUAlp.gif)
