### ISSUE TITLE
On macOS Catalina (10.15.1), `npm install blinkstick` Fails

### ISSUE THREAD

**Issue by coffeepostal** [arvydas/blinkstick-node#37]
I'm following the installation guide in the README, but when I try to install run: `npm i blinkstick`, it errors out. Usually I Google the errors to figure out that I running the wrong versions of Node or something, but I'm coming up empty. I've attached the log file for those who understand them, but here are just the error lines:
```
2885 error code ELIFECYCLE
2886 error errno 1
2887 error usb@1.1.1 install: `node-pre-gyp install --fallback-to-build`
2887 error Exit status 1
2888 error Failed at the usb@1.1.1 install script.
2888 error This is probably not a problem with npm. There is likely additional logging output above.
```

Thanks!
[2019-11-14T21_25_56_903Z-debug.log](https://github.com/arvydas/blinkstick-node/files/3848714/2019-11-14T21_25_56_903Z-debug.log)

**Comment by coffeepostal** [comment]
I kind of fixed it, I downgraded to Node v8, and that allowed me to install the module, but I had to install [node-hid](https://github.com/node-hid/node-hid#installation) to get it to work. I'd also manually installed usb, node-gyp, and node-pre-gyp, so I'm not exactly sure what the combination was that fixed it, but I'm at least getting some response from the BlinkStick.

**Comment by grantglidewell** [comment]
Mine works with a package.json dependencies list that looks like:
```
  "dependencies": {
    "blinkstick": "^1.1.3",
    "node-gyp": "^6.0.1",
    "node-hid": "^1.1.0",
    "node-pre-gyp": "^0.14.0",
    "usb": "^1.6.2"
  }
```
running node version 8.16.12

**Comment by arvydas** [comment]
Just a quick update that new version 1.2.0 of module now works with Catalina.
