### ISSUE TITLE
cannot set color on led index 0

### ISSUE THREAD

**Issue by fakkio** [arvydas/blinkstick-node#40]
Hi,
I have a BlinkStick Square. I cannot use setColor to change led with index = 0.
If I try to use: 
```
device.setColor("random", 0);
```
it will set the color on all 8 LEDs. Is there a way to set led with index 0 individually?

TY,
Fabio.

**Comment by arvydas** [comment]
What is the mode of your Square?

**Comment by fakkio** [comment]
I don't know, how can I check?

EDIT:
ok, I did `device.getMode()` and it returns 3.
Which mode should I use?

**Comment by arvydas** [comment]
Switch to mode 2

**Comment by fakkio** [comment]
Thanks,
it works perfectly

Fabio.
